# This is the network config written by 'subiquity'
network:
  ethernets:
    eno6:
      addresses:
        -  x.x.x.x/x
      routes:
        - to: default
          via: x.x.x.x
      nameservers:
        addresses: [10.131.168.16]
      emit-lldp: true
      optional: true
  bridges:
    brha:
      interfaces: [  ]
      optional: true
  version: 2
